[package]
name = "lattice_crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
# leech-lattice = { git = "https://github.com/some-crypto-researcher/leech-lattice.git", branch = "main" } # Placeholder
