[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
# We will need a networking library, e.g., libp2p
# libp2p = { version = "0.44", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
