[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.44", features = ["tcp-tokio", "ping"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
